#!/bin/bash
touch textarr.txt
touch out.txt
g++ createRandomArr.cpp -o randArr

Set=(0 1 2 3 s g fast)
for n in 50000 55000 57000; do
	./randArr $n
	echo "Compil with $n size array"
	for opt in "${Set[@]}"; do
		min_time=9999999999
		g++ -O"$opt" main.cpp -o mainO"$opt"
		echo "Compile with level O"$opt""
		for ((i = 1; i <= 10; i++)); do
			val=$(./mainO"$opt")
			if (( $(echo "$val < $min_time" | bc -l) )); then
				min_time=$val
			fi
		done
		echo "Min time = $min_time"
		rm mainO"$opt"
	done
done

# Удалить временные файлы
rm textarr.txt
rm out.txt
rm randArr

